SQL_FILM_DETAILS = '''select distinct
        f.FILM_ID,
        f.FILM_HO_CODE,
        COALESCE(m.FILM, f.FILM) AS FILM_TITLE,
        d.DSTBTR AS DISTRIBUTOR_NAME,
        d.DSTRBTR_ID AS DISTRIBUTOR,
        g1.GNRE_1 AS GENRE_1_NAME,
        g2.GNRE_1 AS GENRE_2_NAME,
        g3.GNRE_1 AS GENRE_3_NAME,
        g1.GNRE_1_ID AS GENRE_1,
        g2.GNRE_1_ID AS GENRE_2,
        g3.GNRE_1_ID AS GENRE_3,
        f.FIL_DURN AS FILM_DURATION,
        FILM_NAT_OPEN_DATE,
        FIL_OPEN_DATE AS FILM_OPEN_DATE,
        WEEKISO(COALESCE(FILM_NAT_OPEN_DATE, FIL_OPEN_DATE)) AS RELEASE_WEEK,
        MONTH(COALESCE(FILM_NAT_OPEN_DATE, FIL_OPEN_DATE)) AS RELEASE_MONTH,
        m.ACTORS AS ACTOR_LIST,
        m.DIRECTORS AS DIRECTOR_LIST,
        COALESCE(m.SYNOPSIS, f.FILM_DESC) AS SYNOPSIS,
        CASE WHEN f.FILM_DESC = COALESCE(m.SYNOPSIS, f.FILM_DESC) THEN NULL ELSE f.FILM_DESC END AS ALT_SYNOPSIS,
        RATING_ID,
        CASE WHEN STARTSWITH(f.FILM, '3D') THEN TRUE ELSE FALSE END AS IS_3D_VERSION
    from EDW_ENT_PRD.CURATED.DIM_VH_FILM AS f
    left join EDW_ENT_PRD.CURATED.DIM_VH_GNRE_1 AS g1 ON g1.GNRE_1_ID = f.GNRE1_ID
    left join EDW_ENT_PRD.CURATED.DIM_VH_GNRE_1 AS g2 ON g2.GNRE_1_ID = f.GNRE2_ID
    left join EDW_ENT_PRD.CURATED.DIM_VH_GNRE_1 AS g3 ON g3.GNRE_1_ID = f.GNRE3_ID
    left join EDW_ENT_PRD.CURATED.DIM_VH_DSTRBTR AS d ON d.DSTRBTR_ID = f.DSTRBTR_ID
    left join ENT_FORECAST_PRD.SEMANTIC.FORECAST_IHUB_MOVIE_AU AS m ON m.FILM_HO_CODE = f.FILM_HO_CODE
    where FILM_NAT_OPEN_DATE is not null
'''


SQL_FILMS_BY_RELEASE_OUTER = '''
    SELECT 
        DENSE_RANK() OVER(ORDER BY FILM_OPEN_DATE) AS RELEASE_DATE_ID,
        FILM_OPEN_DATE AS RELEASE_DATE,
        ROW_NUMBER() OVER(PARTITION BY FILM_OPEN_DATE ORDER BY FILM) AS RELEASE_DATE_FILM_ID,
        FILM_ID,
        FILM
    FROM
    (
        SELECT '2026-04-22' AS FILM_OPEN_DATE, FILM_ID, FILM from EDW_ENT_PRD.CURATED.DIM_VH_FILM 
        WHERE FIL_OPEN_DATE BETWEEN '2026-04-22' AND '2026-04-29'
        UNION
        SELECT '2026-05-07' AS FILM_OPEN_DATE, FILM_ID, FILM from EDW_ENT_PRD.CURATED.DIM_VH_FILM 
        WHERE FIL_OPEN_DATE BETWEEN '2026-05-07' AND '2026-05-13'
        UNION
        SELECT '2026-05-21' AS FILM_OPEN_DATE, FILM_ID, FILM from EDW_ENT_PRD.CURATED.DIM_VH_FILM 
        WHERE FIL_OPEN_DATE BETWEEN '2026-05-21' AND '2026-05-27'
    ) AS f
    WHERE FILM NOT ILIKE 'GC %'
'''

SQL_FILMS_BY_RELEASE = '''
    SELECT
        :release_date AS RELEASE_DATE, 
        FILM_ID, 
        FILM 
    FROM EDW_ENT_PRD.CURATED.DIM_VH_FILM 
    WHERE 
        FIL_OPEN_DATE BETWEEN :release_date AND DATEADD(DAY, 6, :release_date)
        AND FILM NOT ILIKE 'GC %'
'''
