SQL_CURRENT_SYNOPSES = '''
    SELECT 
        e.*  EXCLUDE (TITLE, SYNOPSES_ID, LOADED_TIMESTAMP), 
        COALESCE(m.MOVIE_NAME, f.FILM) AS TITLE, 
        COALESCE(m.SYNOPSIS, f.FILM_DESC) AS SYNOPSIS
    FROM ENT_FORECAST_PRD.CURATED.FILM_SYNOPSES_EXTRACTED AS e
    LEFT JOIN EDW_ENT_PRD.CURATED.DIM_VH_FILM AS f ON f.FILM_ID = e.FILM_ID
    LEFT JOIN EDW_ENT_PRD.CURATED.S2S_IHUB_MOVIE_AU AS m ON m.MOVIE_CODE = f.FILM_HO_CODE
'''

SQL_STAGING_TABLE = 'ENT_FORECAST_PRD.STAGING.FILM_SYNOPSES_EXTRACTED'

SQL_DELETE_STAGING_DEDUPE = '''
    DELETE FROM ENT_FORECAST_PRD.STAGING.FILM_SYNOPSES_EXTRACTED 
    WHERE FILM_ID IN (
        SELECT FILM_ID
        FROM (
            SELECT
                FILM_ID,
                ROW_NUMBER() OVER (
                    PARTITION BY FILM_ID
                    ORDER BY LOADED_TIMESTAMP DESC, FILM_ID
                ) AS rn
            FROM ENT_FORECAST_PRD.STAGING.FILM_SYNOPSES_EXTRACTED 
        )
        WHERE rn > 1
    );
'''

SQL_UPDATE_STAGING_VARIANTS = '''
    UPDATE ENT_FORECAST_PRD.STAGING.FILM_SYNOPSES_EXTRACTED
    SET
        PEOPLE = IFF(TYPEOF(PEOPLE) = 'VARCHAR', TRY_PARSE_JSON(PEOPLE::string), PEOPLE),
        THEMES = IFF(TYPEOF(THEMES) = 'VARCHAR', TRY_PARSE_JSON(THEMES::string), THEMES),
        INTELLECTUAL_PROPERTY = IFF(TYPEOF(INTELLECTUAL_PROPERTY) = 'VARCHAR', TRY_PARSE_JSON(INTELLECTUAL_PROPERTY::string), INTELLECTUAL_PROPERTY),
        GENRES = IFF(TYPEOF(GENRES) = 'VARCHAR', TRY_PARSE_JSON(GENRES::string), GENRES),
        SUBGENRES = IFF(TYPEOF(SUBGENRES) = 'VARCHAR', TRY_PARSE_JSON(SUBGENRES::string), SUBGENRES),
        SETTING_TYPES = IFF(TYPEOF(SETTING_TYPES) = 'VARCHAR', TRY_PARSE_JSON(SETTING_TYPES::string), SETTING_TYPES),
        TIME_PERIODS = IFF(TYPEOF(TIME_PERIODS) = 'VARCHAR', TRY_PARSE_JSON(TIME_PERIODS::string), TIME_PERIODS),
        PROTAGONIST_ARCHETYPES = IFF(TYPEOF(PROTAGONIST_ARCHETYPES) = 'VARCHAR', TRY_PARSE_JSON(PROTAGONIST_ARCHETYPES::string), PROTAGONIST_ARCHETYPES),
        TONE = IFF(TYPEOF(TONE) = 'VARCHAR', TRY_PARSE_JSON(TONE::string), TONE),
        LANGUAGE_CUES = IFF(TYPEOF(LANGUAGE_CUES) = 'VARCHAR', TRY_PARSE_JSON(LANGUAGE_CUES::string), LANGUAGE_CUES),
        SECONDARY_AUDIENCES = IFF(TYPEOF(SECONDARY_AUDIENCES) = 'VARCHAR', TRY_PARSE_JSON(SECONDARY_AUDIENCES::string), SECONDARY_AUDIENCES)
  '''

SQL_MERGE_STAGING_TO_CURATED = '''
    MERGE INTO ENT_FORECAST_PRD.CURATED.FILM_SYNOPSES_EXTRACTED AS t
    USING ENT_FORECAST_PRD.STAGING.FILM_SYNOPSES_EXTRACTED AS s
    ON t.FILM_ID = s.FILM_ID
    WHEN MATCHED
        THEN UPDATE 
            ALL BY NAME 
    WHEN NOT MATCHED 
        THEN INSERT 
            ALL BY NAME;
'''
